---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:

  - name: Creating vm
    ec2:
#       instance_type: a1.medium
       instance_type: t2.micro
       key_name: key
       image: ami-08cec7c429219e339
       region: us-east-2
       group: default
       vpc_subnet_id: subnet-a0a052cb
       count: 1
       wait: yes
       assign_public_ip: yes
    register: vm
